[package]
name = "aoc2020_04b"
version = "0.1.0"
authors = ["Giovanni Foiani <giovanni.foiani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"

[[bin]]
name = "aoc2020_04b"
path = "main.rs"
